config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: %i[show edit update index] do
    resources :posts, only: %i[show new create update edit destroy] do
      resources :comments
      resources :likes, only: %i[create destroy]
    end
    resources :followers, only: :index
    resources :followings, only: :index
  end

  resources :follows, only: %i[create destroy]
  resources :feed_posts, only: [:index]
  resources :search, only: [:index]

  devise_scope :user do
    get "/" => "devise/sessions#new"
  end

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :post

  validates :comment_text, presence: true, length: { maximum: 150 }
  validates :user_id, presence: true
  validates :post_id, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :load_user
  before_action :load_post


  def new
    @comment = Comment.new
  end

  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to user_post_path(@user, @post), flash: { success: "Comment was add" }
    else
      render :new, flash: { alert: "Some error occured" }
    end
  end

  def destroy
    if @post.comments.find_by(id: params[:id]).present?
      @comment = @post.comments.find(params[:id])
      @comment.destroy
      redirect_to user_post_path(@post.user, @post)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_text)
  end

  def load_user
    @user = User.find(params[:user_id])
  end

  def load_post
    @post = Post.find(params[:post_id])
  end
end

app/views/comments/_form.html.haml
= form_with(model: [user, post, comment], local: true) do |form|
  - if comment.errors.any?
    #error_explanation
      %h2
        = pluralize(comment.errors.count, 'error')
        prohibited this post from being saved:
      %ul
        - comment.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :comment_text
    = form.text_field :comment_text
  .actions
    = form.submit

app/views/comments/_index.html.haml
%h2 Comments
- @comments.each do |comment|
  %p
    = link_to(comment.user.name, user_path(comment.user))
    \: #{comment.comment_text}
    - if current_user == comment.user
      %button.btn.btn-outline-secondary{:type => "button"}
        = link_to "Delete comment", user_post_comment_path(comment.user, comment.post, comment.id), method: :delete, |
          data: { confirm: 'Are you sure?' }                                                                         |

app/views/comments/new.html.haml
%h1 New comment
= render 'comments/form', user: @user, post: @post, comment: @comment
= link_to 'back', user_post_path(@user, @post)