config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: %i[show edit update index] do
    resources :posts, only: %i[show new create update edit destroy] do
      resources :comments
      resources :likes, only: %i[create destroy]
    end
    resources :followers, only: :index
    resources :followings, only: :index
  end

  resources :follows, only: %i[create destroy]
  resources :feed_posts, only: [:index]
  resources :search, only: [:index]

  devise_scope :user do
    get "/" => "devise/sessions#new"
  end

end

app/models/user.rb
# frozen_string_literal: true
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  include ImageUploader::Attachment.new(:image)

  include PgSearch::Model
  pg_search_scope :search_by_user, against: :name

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  has_many :follower_follows, foreign_key: :following_id, class_name: "Follow", dependent: :destroy
  has_many :followers, through: :follower_follows, source: :follower, dependent: :destroy

  has_many :following_follows, foreign_key: :follower_id, class_name: "Follow", dependent: :destroy
  has_many :followings, through: :following_follows, source: :following, dependent: :destroy

  CONST_VALID_EMAIL = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

  validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 100},
            format: { with: CONST_VALID_EMAIL, message: 'Invalid email' }
  validates :name, presence: true, length: { maximum: 50 }
  validates :bio, presence: true, length: { maximum: 50 }

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: %i[edit update]

  def index
    @users = User.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_update_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

    private

  def user_update_params
    params.require(:user).permit(:name, :bio, :image)
  end

end

app/views/users/edit.html.haml
.user-edit
  %h1 Edit user info
  = form_with(model: @user, local: true) do |form|
    - if @user.errors.any?
      #error_explanation
        %h2
          = pluralize(post.errors.count, 'error')
          prohibited this post from being saved:
        %ul
          - @user.errors.full_messages.each do |message|
            %li= message
    .field
      = form.label :name
      = form.text_area :name
    .field
      = form.label :bio
      = form.text_area :bio
    .field
      = form.label :avatar
      = form.hidden_field :image, value: @user.cached_image_data
      = form.file_field :image
    %br/
    .actions
      = form.submit

app/views/users/index.html.haml
%h1 User list
.container.my-5
  .row
    - @users.each do |user|
      .col-md-2.center
        .avatar
          = image_tag user.image_url(:small)
        %p
          = link_to "#{user.name}", user_path(user)
.center= paginate @users

app/views/users/show.html.haml
.row
  .col-md-4.avatar-box
    .avatar
      = image_tag @user.image_url(:small)
  .col-md-4
    %h4 User info
    %p
      Name:
      %strong= @user.name
    = succeed "Bio:" do
      %p
    %strong= @user.bio
    = succeed "Email:" do
      %p
    %strong= @user.email
  .col-md-4
    %br/
    = link_to "Posts: #{@user.posts.size}", user_path(@user)
    %br/
    - if current_user == @user
      = link_to "Feed posts", feed_posts_path(@user)
    %br/
    = link_to "Followers: #{@user.followers.size}", user_followers_path(@user)
    %br/
    = link_to "Following: #{@user.followings.size}", user_followings_path(@user)
    %br/
    - if current_user.present? && current_user != @user
      - if current_user.followings.include?(@user)
        = link_to("Unfollow", follow_path(following_id: @user.id), method: :delete)
      - else
        = link_to("Follow", follows_path(following_id: @user.id), method: :post)
%h1= "#{@user.name} posts"
= render "posts/index"