config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: %i[show edit update index] do
    resources :posts, only: %i[show new create update edit destroy] do
      resources :comments
      resources :likes, only: %i[create destroy]
    end
    resources :followers, only: :index
    resources :followings, only: :index
  end

  resources :follows, only: %i[create destroy]
  resources :feed_posts, only: [:index]
  resources :search, only: [:index]

  devise_scope :user do
    get "/" => "devise/sessions#new"
  end

end

app/models/post.rb
# frozen_string_literal: true
class Post < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, length: { maximum: 150 }
  validates :image_data, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :load_user

  def show
    @post = @user.posts.find(params[:id])
    @comments = @post.comments
    @comment = Comment.new
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = @user
    if @post.save
      redirect_to user_post_path(@user, @post), flash: { success: "Post was add" }
    else
      render :new, flash: { alert: "Some error occured" }
    end
  end

  def edit
    @post = @user.posts.find(params[:id])
    authorize @post
  end

  def update
    @post = @user.posts.find(params[:id])
    authorize @post
    if @post.update(post_params)
      redirect_to user_post_path(@user, @post), flash: { success: "Post was update"}
    else
      render :edit, flash: { alert: "Some error occured" }
    end
  end

  def destroy
    @post = @user.posts.find(params[:id])
    authorize @post
    @post.destroy
    redirect_to user_path(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

  def load_user
    @user = User.find(params[:user_id])
  end

end

app/views/posts/_form.html.haml
= form_with(model: [user, post], local: true) do |form|
  - if post.errors.any?
    #error_explanation
      %h2
        = pluralize(post.errors.count, 'error')
        prohibited this post from being saved:
      %ul
        - post.errors.full_messages.each do |message|
          %li= message
  .field.center
    = form.label :title
    = form.text_area :title
  .field.center
    = form.label :body
    = form.text_area :body
  .field.center
    = form.label :your_post_image
    = form.hidden_field :image, value: @post.cached_image_data
    = form.file_field :image
  %br/
  .actions.center
    = form.submit

app/views/posts/_index.html.haml
.container.my-5
  .row
    - @posts.each do |post|
      .col-md-4
        %h2= post.title
        = image_tag post.image_url(:medium)
        %p= link_to(post.user.name, user_path(post.user))
        %p= "Body: #{post.body}"
        %p
          = "Like: #{post.likes.count}"
          - if Like.find_by(user: current_user, post: post).present?
            = link_to "Unlike", user_post_like_path(@user, post), method: :delete
          - else
            = link_to "Like", user_post_likes_path(@user, post), method: :post
        = link_to "Show", user_post_path(@user, post)

app/views/posts/edit.html.haml
%h1 Edit Post
= render 'form', user: @user, post: @post
%p{:style => "text-align: center"}
  = link_to 'Back', user_post_path(@user, @post)

app/views/posts/new.html.haml
.new-post
  %h1 New Post
  = render 'posts/form', user: @user, post: @post
  = link_to 'back', user_path(@user, @post)

app/views/posts/show.html.haml
.container.center
  %h1
    = @post.title
  = image_tag @post.image_url(:large)
  %p= @post.body
  %p
    = "Number of likes: #{@post.likes.count}"
    %button.btn.btn-outline-secondary{:type => "button"}
      - if Like.find_by(user: current_user, post: @post).present?
        = link_to "Unlike", user_post_like_path(@user, @post), method: :delete
      - else
        = link_to "Like", user_post_likes_path(@user, @post), method: :post
    - if current_user == @user
      - if policy(@post).update?
        %button.btn.btn-outline-secondary{:type => "button"}
          = link_to "Edit", edit_user_post_path(current_user, @post)
        %button.btn.btn-outline-danger{:type => "button"}
          = link_to "Delete post", user_post_path(current_user, @post), method: :delete, |
            data: { confirm: 'Are you sure?' }                                           |
  = render 'comments/index'
  = render 'comments/form', user: @user, post: @post, comment: @comment