config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: %i[show edit update index] do
    resources :posts, only: %i[show new create update edit destroy] do
      resources :comments
      resources :likes, only: %i[create destroy]
    end
    resources :followers, only: :index
    resources :followings, only: :index
  end

  resources :follows, only: %i[create destroy]
  resources :feed_posts, only: [:index]
  resources :search, only: [:index]

  devise_scope :user do
    get "/" => "devise/sessions#new"
  end

end

app/views/layouts/_header.html.haml
%header
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    - if current_user.present?
      = link_to "Instagram", user_path(current_user), id: "logo"
    - else
      = link_to "Instagram", new_user_session_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= render "search/search"
        %li= link_to "Users list", users_path
        - if current_user.present?
          %li= link_to "New post", new_user_post_path(current_user)
          %li= link_to "Edit Profile", edit_user_path(current_user)
          %li= link_to "Sign out", destroy_user_session_path, method: :delete
        - else
          %li= link_to "Sign_in", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Instagram
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    %link{"data-turbolinks-track" => "true", :href => "/assets/application.css", :media => "all", :rel => "stylesheet"}/
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %p.notice= notice
    %p.alert= alert
    = render "layouts/header"
    .container-fuild
      = yield